# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=64)),
                ('method', models.CharField(default='GET', max_length=32)),
                ('url', models.CharField(max_length=255)),
                ('request', models.TextField(blank=True)),
                ('response', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
